[package]
name = "oxidation"
version = "0.1.0"
edition = "2021"

[dependencies]


[dependencies.windows]
version = "0.58.0"
features = [
    "Foundation_Collections",
    "Win32_Foundation",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Memory",
    "Win32_System_Threading",
    "Win32_Security",
]